# Build and deploy a Next.js site to GitHub Pages
# https://gist.github.com/dev-zha/5a4ae45c7c981aa024dd7d6b269b6cb8

name: Deploy to GitHub Pages

on:
  push:
    branches: ['master', 'feat/deploy-workflow']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:

  deploy:
    needs: build
