import type { Metadata } from 'next';
import { Antonio, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';

const antonioSans = Antonio({
  variable: '--font-antonio',
  weight: ['700'],
  subsets: ['latin'],
});

const jakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${antonioSans.variable} ${jakartaSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
