name: Waka Readme

on:
  schedule:
    # Runs twice at 5am and 5pm UTC (12am and 12pm GMT+7)
    - cron: '0 5,17 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: 'True'
          SHOW_DAYS_OF_WEEK: 'False'
          SHOW_TIMEZONE: 'False'
          SHOW_LANGUAGE: 'False'
          SHOW_EDITORS: 'False'
          SHOW_PROJECTS: 'True'
          SHOW_OS: 'False'
          SHOW_LOC_CHART: 'False'
